### ISSUE TITLE
How to access to triangle data from hex.Address

### ISSUE THREAD

**Issue by geotyper** [Khayetan/UE4HexsphereMapGeneratorPlugin#1]
![image](https://user-images.githubusercontent.com/30755433/147393208-d96b79d7-d566-4542-a923-1fb050e9ceae.png)
Port this library to c++ with OpenGL. All works well.
But I want to assign color to Hex vertices, but cant access to them. HesSphereMapData gave Geometry and Hexes, but where store relations between Hex and its vertices and triangles?

**Comment by geotyper** [comment]
![image](https://user-images.githubusercontent.com/30755433/147393319-2f8b9070-f799-4e57-9cb3-9d72eec52731.png)
I try to do like this code, but have question: HexSphereMapData::GetHexSideMeshData(int HexID, int SideID)
what is SideID? if it is one side of 6 hex sides?
Found that it retrun number of Tri in Hex in local index: for example for Hex=0 side=0 tri=6 (0,1,2) (0,2,3) but how find number of this Tri in global Geometry.Tri?

**Comment by geotyper** [comment]
and one more question:
![image](https://user-images.githubusercontent.com/30755433/147393563-953b04d1-1c41-4876-a979-ff269af9ffc7.png)
why in Hex with Address 0 in Neighbours  it own address in position 6(or index 5 in array)?
and why blsPents=true for first 12 Hexes?

**Comment by Khayetan** [comment]
> But I want to assign color to Hex vertices, but cant access to them. HesSphereMapData gave Geometry and Hexes, but where store relations between Hex and its vertices and triangles?

Each side has 4 verts, the reason for it is that allows you to distort each hex to make the map look more natural.
Anyway, each side has 4 verts, the way you calculate the index of each vert goes like this: 
a: the index of the hex
b: the index of the side
c: the index of the vert you're looking for, locally, so between 0 and 3

(a * 24) + (b * 4) + c
(24 is how many verts there are in a single hex, 4 is how many there are in a single side)

Or something like that. It's been a while since I made this thing, but that should put you on the right track.

> what is SideID? if it is one side of 6 hex sides?

SideID is named a little confusingly, it's the local id of the neighbouring side. This can be used to coordinate texture blending between tiles and such.

> Found that it retrun number of Tri in Hex in local index: for example for Hex=0 side=0 tri=6 (0,1,2) (0,2,3) but how find number of this Tri in global Geometry.Tri?

You would have to apply a similar formula as I've given previously, something like (a * 36) + (b * 6) + c
Where c is the index of the tri, locally.
Probably should've made a function for that.


> why in Hex with Address 0 in Neighbours it own address in position 6(or index 5 in array)?
and why blsPents=true for first 12 Hexes?

Well that's quite simple really. An icosahedron divided into hexes will always have 12 pentagons, you cannot have a sphere made purely out of hexagons, it's mathematically impossible. 
So the first 12 "hexes" are actually pentagons, and they use the same data structure to simplify calculations.

I hope you will find this answer useful.

**Comment by geotyper** [comment]
Thanks, your comment help.
And one more simple question: vertices are different for different hex, or hex have the same vertices for there neighbors , another words, you duplicate vertices for different hex?

**Comment by geotyper** [comment]
![image](https://user-images.githubusercontent.com/30755433/147401649-0e4f1eba-f28e-459b-9f0e-be03fb957b72.png)
think it works well, open your code only yesterday evening and this morning have a result, thank again for share code.

**Comment by Khayetan** [comment]
> And one more simple question: vertices are different for different hex, or hex have the same vertices for there neighbors , another words, you duplicate vertices for different hex?

Each hex has it's own verts, otherwise you wouldn't be able to texture each tile individually using UVs.
